import type { Scenario } from "./types";

/** Scenario corpus, part 3 of 3 — infrastructure, cyber and maritime friction. */
export const SCENARIOS_3: Scenario[] = [
  {
    id: "MER-4158",
    reference: "TRD/ARC/01",
    title: "First full-season Northern Sea Route transit claims",
    summary:
      "Two operators have claimed season-long regular service on the Northern Sea Route, and a third has published a full transit schedule, moving the route from experimental to scheduled in commercial terms.",
    stage: "emerging",
    detectedAt: "2026-09-14",
    firstSignalAt: "2026-08-20",
    confidence: 0.7,
    novelty: 0.89,
    velocity: 0.47,
    actors: ["RU", "CN", "SG", "NL", "EU", "US"],
    regions: ["Arctic", "Asia-Pacific", "Europe"],
    tags: ["shipping", "corridor", "logistics"],
    analystNote:
      "A route becomes structurally significant when insurers price it, not when ships use it. Watch underwriting capacity rather than transit counts — that is the binding constraint.",
    tailScenario:
      "An underwriter withdraws Arctic hull-and-cargo cover after a single loss event, and the schedule is withdrawn with it. Route status is set by capital allocation, which is reversible on a single claim.",
    signals: [
      {
        id: "S-4158-1",
        source: "Operator schedule publication",
        sourceClass: "official",
        observedAt: "2026-08-20",
        channel: "trade",
        headline: "Full-season published transit schedule",
        detail: "A schedule is a commercial commitment; prior transits were opportunistic and unpublished.",
        reliability: 0.88,
        weight: 0.68,
        corroborations: 3,
        anomalyZ: 2.2,
      },
      {
        id: "S-4158-2",
        source: "Northern European insurance market",
        sourceClass: "market",
        observedAt: "2026-08-30",
        channel: "finance",
        headline: "Arctic cover offered at standard terms for a third consecutive season",
        detail: "Standard terms, not discounted terms, is the meaningful threshold in this market.",
        reliability: 0.86,
        weight: 0.74,
        corroborations: 4,
        anomalyZ: 2.6,
      },
      {
        id: "S-4158-3",
        source: "Ice-class fleet tracker",
        sourceClass: "intel",
        observedAt: "2026-09-06",
        channel: "trade",
        headline: "Ice-class orderbook extends to 2029",
        detail: "Fleet investment is the only durable signal here; transits are weather-dependent noise.",
        reliability: 0.8,
        weight: 0.66,
        corroborations: 3,
        anomalyZ: 2.1,
      },
      {
        id: "S-4158-4",
        source: "Arctic council technical briefing",
        sourceClass: "official",
        observedAt: "2026-09-14",
        channel: "diplomatic",
        headline: "Transit governance rules extended to a further vessel class",
        detail: "Procedural recognition by a non-routing state reduces the geopolitical discount on the route.",
        reliability: 0.84,
        weight: 0.5,
        corroborations: 2,
        anomalyZ: 1.6,
      },
    ],
    pathways: [
      {
        channel: "trade",
        direction: "mixed",
        magnitude: 0.47,
        lagDays: [90, 400],
        confidence: 0.6,
        mechanism:
          "Substitution, not disruption. The effect is a small permanent discount on Asia–Europe routing, which requires enough tonnage to matter and enough reliability to schedule around.",
        exposures: [
          { nodeId: "ARCTIC", exposure: 0.8, impact: 0.44, lagDays: 120, note: "Route normalised in scheduling systems" },
          { nodeId: "RU", exposure: 0.72, impact: 0.38, lagDays: 140, note: "Transit revenue and port fees accrue" },
          { nodeId: "SG", exposure: 0.58, impact: 0.26, lagDays: 160, note: "Transhipment volume shifts to northern routing" },
          { nodeId: "EU", exposure: 0.5, impact: 0.21, lagDays: 150, note: "Rotterdam and Hamburg call patterns change" },
          { nodeId: "SUZK", exposure: 0.42, impact: 0.2, lagDays: 170, note: "Suez economics pressured by diversion" },
        ],
      },
      {
        channel: "finance",
        direction: "mixed",
        magnitude: 0.31,
        lagDays: [60, 200],
        confidence: 0.5,
        mechanism: "Asset values and insurance pricing shift before freight economics do.",
        exposures: [
          { nodeId: "INSTL", exposure: 0.36, impact: 0.15, lagDays: 110, note: "Ice-class asset revaluation" },
          { nodeId: "RU", exposure: 0.42, impact: 0.19, lagDays: 130, note: "Arctic logistics credit expansion" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "mixed",
        magnitude: 0.36,
        lagDays: [90, 300],
        confidence: 0.48,
        mechanism:
          "Recognition without transit-rights equivalence. Governance participation and commercial access remain separable.",
        exposures: [
          { nodeId: "RU", exposure: 0.5, impact: 0.22, lagDays: 130, note: "Sanctions perimeter applied to a new trade route" },
          { nodeId: "EU", exposure: 0.4, impact: 0.16, lagDays: 160, note: "Position on non-Russian hulls under review" },
        ],
      },
      {
        channel: "energy",
        direction: "mixed",
        magnitude: 0.2,
        lagDays: [180, 500],
        confidence: 0.34,
        mechanism: "Negligible on current volumes; relevant only if route reliability becomes structural.",
        exposures: [
          { nodeId: "RU", exposure: 0.3, impact: 0.1, lagDays: 300, note: "Northern-of-Siberian output optionality only" },
        ],
      },
    ],
  },
  {
    id: "MER-4163",
    reference: "NRG/CYB/04",
    title: "Coordinated intrusion campaign against port and energy operators",
    summary:
      "A multi-week intrusion campaign against port authorities and grid-adjacent energy operators has produced two unscheduled outages, with attribution still contested between state and proxy actors.",
    stage: "active",
    detectedAt: "2026-09-27",
    firstSignalAt: "2026-09-12",
    confidence: 0.74,
    novelty: 0.72,
    velocity: 0.83,
    actors: ["RU", "US", "EU", "UA", "TR", "IR"],
    regions: ["Europe", "Eurasia"],
    tags: ["cyber", "critical infrastructure", "energy"],
    analystNote:
      "Cyber events should enter the model at the physical-consequence level, not the intrusion level. The energy coefficient is driven by unscheduled outage duration, which is why attribution confidence stays low while the risk coefficient stays high.",
    tailScenario:
      "A third outage coincides with a scheduled maintenance window, removing the redundancy that absorbed the previous two. Recovery depends on manual operation, and restoration timelines are governed by equipment lead times rather than by technical response.",
    signals: [
      {
        id: "S-4163-1",
        source: "National cyber agency bulletin",
        sourceClass: "official",
        observedAt: "2026-09-12",
        channel: "energy",
        headline: "Coordinated targeting of port and grid-adjacent operators declared",
        detail: "Advisory identifies a shared initial-access vector across at least nine organisations in two jurisdictions.",
        reliability: 0.92,
        weight: 0.82,
        corroborations: 4,
        anomalyZ: 3.2,
      },
      {
        id: "S-4163-2",
        source: "Port authority operational notice",
        sourceClass: "official",
        observedAt: "2026-09-19",
        channel: "trade",
        headline: "Unscheduled berth closure of 31 hours",
        detail: "Closure attributed to a systems fault; the advisory's initial-access date falls three days prior.",
        reliability: 0.88,
        weight: 0.74,
        corroborations: 3,
        anomalyZ: 2.9,
      },
      {
        id: "S-4163-3",
        source: "Regional transmission operator",
        sourceClass: "official",
        observedAt: "2026-09-25",
        channel: "energy",
        headline: "Unscheduled outage of 240MW lasting 19 hours",
        detail: "Restoration conducted manually; no automated load-shedding initiated.",
        reliability: 0.9,
        weight: 0.78,
        corroborations: 4,
        anomalyZ: 3.4,
      },
      {
        id: "S-4163-4",
        source: "Open-source incident tracker",
        sourceClass: "social",
        observedAt: "2026-09-27",
        channel: "diplomatic",
        headline: "Attribution claims issued by two competing states",
        detail: "Competing claims, both with artefact evidence, is itself the informative signal.",
        reliability: 0.41,
        weight: 0.3,
        corroborations: 1,
        anomalyZ: 2.0,
      },
    ],
    pathways: [
      {
        channel: "energy",
        direction: "escalatory",
        magnitude: 0.74,
        lagDays: [3, 60],
        confidence: 0.75,
        mechanism:
          "Cyber impacts the energy channel only when it becomes physical. Outage duration, not intrusion count, is the model input; restoration time is bounded by equipment lead times.",
        exposures: [
          { nodeId: "EU", exposure: 0.8, impact: 0.48, lagDays: 15, note: "Redundancy absorbed both outages; a third exceeds it" },
          { nodeId: "TR", exposure: 0.66, impact: 0.38, lagDays: 22, note: "Grid operator and port systems share identity infrastructure" },
          { nodeId: "RU", exposure: 0.58, impact: 0.31, lagDays: 18, note: "Attribution contested, capability assumed symmetric" },
        ],
      },
      {
        channel: "trade",
        direction: "escalatory",
        magnitude: 0.61,
        lagDays: [5, 45],
        confidence: 0.72,
        mechanism:
          "Port disruption propagates as schedule unreliability, which is costlier than lost volume and persists after the outage ends because recovery backlogs take weeks to clear.",
        exposures: [
          { nodeId: "EU", exposure: 0.76, impact: 0.44, lagDays: 25, note: "Berth scheduling backlog propagates inland" },
          { nodeId: "TR", exposure: 0.62, impact: 0.34, lagDays: 28, note: "Transhipment reliability premium" },
          { nodeId: "NL", exposure: 0.54, impact: 0.28, lagDays: 30, note: "Distribution centre throughput disruption" },
        ],
      },
      {
        channel: "finance",
        direction: "escalatory",
        magnitude: 0.43,
        lagDays: [7, 40],
        confidence: 0.63,
        mechanism:
          "Operational and counterparty risk pricing for utilities and logistics operators; small in absolute terms, persistent in duration.",
        exposures: [
          { nodeId: "INSTL", exposure: 0.44, impact: 0.2, lagDays: 20, note: "Utility and logistics risk premia widen" },
          { nodeId: "EU", exposure: 0.4, impact: 0.18, lagDays: 25, note: "Corporate cyber-insurance repricing" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "escalatory",
        magnitude: 0.66,
        lagDays: [10, 60],
        confidence: 0.6,
        mechanism:
          "Contested attribution removes the accountability channel that normally suppresses escalation. Each disputed claim raises the risk of a misattributed retaliatory response.",
        exposures: [
          { nodeId: "RU", exposure: 0.6, impact: 0.32, lagDays: 20, note: "Attribution denials keep the channel open" },
          { nodeId: "US", exposure: 0.54, impact: 0.27, lagDays: 18, note: "Retaliatory-response thresholds lowered" },
          { nodeId: "EU", exposure: 0.48, impact: 0.22, lagDays: 25, note: "Unified attribution position not achievable" },
        ],
      },
    ],
  },
  {
    id: "MER-4181",
    reference: "DIP/SCS/02",
    title: "Water-cannon and ramming incident at a contested shoal",
    summary:
      "A maritime law-enforcement confrontation at a contested shoal has escalated from water-cannon use to ramming, with two vessels damaged and the incident sequence disputed between the parties.",
    stage: "escalating",
    detectedAt: "2026-09-29",
    firstSignalAt: "2026-09-16",
    confidence: 0.8,
    novelty: 0.67,
    velocity: 0.79,
    actors: ["CN", "PH", "US", "TW", "JP", "EU"],
    regions: ["Asia-Pacific"],
    tags: ["maritime", "law of the sea", "alliance"],
    analystNote:
      "Directly analogous to the Grey Zone Tribunal record: a law-enforcement action converted into a physical confrontation without a threshold being formally crossed. The pattern, not the shoal, is what generalises.",
    tailScenario:
      "An injury or sinking triggers treaty-consultation obligations that neither ally can satisfy without escalation, and the ally whose vessels were not present nonetheless finds itself committed by an existing mutual-defence understanding.",
    signals: [
      {
        id: "S-4181-1",
        source: "Coast guard statement",
        sourceClass: "official",
        observedAt: "2026-09-16",
        channel: "diplomatic",
        headline: "Water-cannon use during law-enforcement approach",
        detail: "Characterised as lawful enforcement; the counterpart characterises it as unprovoked use of force.",
        reliability: 0.89,
        weight: 0.68,
        corroborations: 4,
        anomalyZ: 2.6,
      },
      {
        id: "S-4181-2",
        source: "Maritime tracking analytics",
        sourceClass: "intel",
        observedAt: "2026-09-22",
        channel: "trade",
        headline: "Supply vessels rerouted away from the approach corridor",
        detail: "Commercial operators self-separate from the area without any instruction to do so.",
        reliability: 0.83,
        weight: 0.72,
        corroborations: 4,
        anomalyZ: 3.0,
      },
      {
        id: "S-4181-3",
        source: "Regional diplomatic readout",
        sourceClass: "official",
        observedAt: "2026-09-25",
        channel: "diplomatic",
        headline: "Consultation requested under a prior incident framework",
        detail: "Using an established framework signals the incident is treated as a precedent, not an isolated event.",
        reliability: 0.85,
        weight: 0.6,
        corroborations: 3,
        anomalyZ: 2.1,
      },
      {
        id: "S-4181-4",
        source: "Asian defence desk",
        sourceClass: "intel",
        observedAt: "2026-09-29",
        channel: "finance",
        headline: "Mutual-defence understanding cited in allied briefing",
        detail: "If cited in briefing rather than in a statement, the commitment is being read as applicable.",
        reliability: 0.71,
        weight: 0.56,
        corroborations: 2,
        anomalyZ: 1.9,
      },
    ],
    pathways: [
      {
        channel: "diplomatic",
        direction: "escalatory",
        magnitude: 0.82,
        lagDays: [5, 50],
        confidence: 0.78,
        mechanism:
          "Grey-zone escalation is ratcheting: each step is individually defensible and collectively degrading. Absence of a formal threshold is precisely what allows the ratchet to operate.",
        exposures: [
          { nodeId: "CN", exposure: 0.82, impact: 0.52, lagDays: 15, note: "Position hardened; retreat read as concession" },
          { nodeId: "PH", exposure: 0.7, impact: 0.45, lagDays: 14, note: "Alliance reliance tested against a direct incident" },
          { nodeId: "US", exposure: 0.62, impact: 0.36, lagDays: 18, note: "Treaty scope becomes the operative question" },
          { nodeId: "JP", exposure: 0.56, impact: 0.31, lagDays: 20, note: "Domestic political constraint sharpens" },
          { nodeId: "EU", exposure: 0.44, impact: 0.22, lagDays: 25, note: "Economic exposure acknowledged without a legal position" },
        ],
      },
      {
        channel: "trade",
        direction: "escalatory",
        magnitude: 0.54,
        lagDays: [10, 60],
        confidence: 0.68,
        mechanism:
          "Voluntary commercial separation from a contested corridor is fast, cheap and reversible — which means it can appear and disappear without any official decision.",
        exposures: [
          { nodeId: "PH", exposure: 0.66, impact: 0.36, lagDays: 22, note: "Approach corridor abandoned by commercial traffic" },
          { nodeId: "TW", exposure: 0.5, impact: 0.24, lagDays: 25, note: "Adjacent routing adjusted" },
        ],
      },
      {
        channel: "energy",
        direction: "mixed",
        magnitude: 0.26,
        lagDays: [60, 160],
        confidence: 0.44,
        mechanism:
          "Indirect through rerouting of LNG and agricultural bulk, where the region absorbs a premium rather than a volume loss.",
        exposures: [
          { nodeId: "JP", exposure: 0.4, impact: 0.2, lagDays: 80, note: "Regional sourcing premium" },
          { nodeId: "TW", exposure: 0.32, impact: 0.15, lagDays: 85, note: "Transhipment surcharge" },
        ],
      },
      {
        channel: "finance",
        direction: "mixed",
        magnitude: 0.38,
        lagDays: [8, 35],
        confidence: 0.6,
        mechanism: "Tail-risk pricing: skew steepens without a corresponding move in spot levels.",
        exposures: [
          { nodeId: "INSTL", exposure: 0.5, impact: 0.23, lagDays: 15, note: "Regional equity skew and volatility steepening" },
          { nodeId: "TW", exposure: 0.42, impact: 0.19, lagDays: 14, note: "Defence and shipping repricing" },
        ],
      },
    ],
  },
  {
    id: "MER-4188",
    reference: "TRD/CUO/02",
    title: "Refining capacity concentration becomes binding after maintenance deferrals",
    summary:
      "Deferrals across three refining assets in one quarter have left a single region without adequate spare distillation capacity, converting a structural concentration into a present-tense operational constraint.",
    stage: "emerging",
    detectedAt: "2026-10-01",
    firstSignalAt: "2026-09-18",
    confidence: 0.72,
    novelty: 0.68,
    velocity: 0.58,
    actors: ["IN", "US", "SG", "KR", "CN"],
    regions: ["South Asia", "North America"],
    tags: ["energy", "infrastructure", "concentration risk"],
    analystNote:
      "A structural risk that becomes operational. The concentration has been static for years; what changed is the maintenance calendar, which means the constraint is discretionary and can be reversed.",
    tailScenario:
      "An unplanned outage at the remaining asset in the constrained region removes effective slack. Import cover is drawn down faster than replacement cargo can be contracted, and regional benchmark differentials invert.",
    signals: [
      {
        id: "S-4188-1",
        source: "Operator filings",
        sourceClass: "official",
        observedAt: "2026-09-18",
        channel: "energy",
        headline: "Turnaround deferred at three assets in the same quarter",
        detail: "Deferrals were individually justified on economics and collectively remove regional slack.",
        reliability: 0.9,
        weight: 0.76,
        corroborations: 3,
        anomalyZ: 2.5,
      },
      {
        id: "S-4188-2",
        source: "Product cracks desk",
        sourceClass: "market",
        observedAt: "2026-09-24",
        channel: "energy",
        headline: "Regional middle-distillate crack at a three-year high",
        detail: "Crack strength with flat crude differentials isolates refining rather than crude as the binding constraint.",
        reliability: 0.86,
        weight: 0.72,
        corroborations: 4,
        anomalyZ: 2.8,
      },
      {
        id: "S-4188-3",
        source: "Trade statistics extract",
        sourceClass: "market",
        observedAt: "2026-09-29",
        channel: "trade",
        headline: "Net product imports up 31% over two months",
        detail: "Import substitution is the market's own answer to the capacity shortfall, and it is already running.",
        reliability: 0.82,
        weight: 0.64,
        corroborations: 3,
        anomalyZ: 2.2,
      },
      {
        id: "S-4188-4",
        source: "Ministry of energy briefing",
        sourceClass: "official",
        observedAt: "2026-10-01",
        channel: "diplomatic",
        headline: "Import sourcing discussions opened with two suppliers",
        detail: "Sourcing discussions imply the shortfall is planned around rather than resolved.",
        reliability: 0.84,
        weight: 0.48,
        corroborations: 2,
        anomalyZ: 1.5,
      },
    ],
    pathways: [
      {
        channel: "energy",
        direction: "escalatory",
        magnitude: 0.68,
        lagDays: [10, 60],
        confidence: 0.76,
        mechanism:
          "Refining capacity is not fungible across grades or regions on a 60-day horizon, so a small slack number becomes a large price response. Crude availability is not the constraint; distillation is.",
        exposures: [
          { nodeId: "IN", exposure: 0.86, impact: 0.56, lagDays: 20, note: "Regional slack exhausted; import cover drawn down" },
          { nodeId: "SG", exposure: 0.6, impact: 0.32, lagDays: 25, note: "Storage arbitrage widens" },
          { nodeId: "KR", exposure: 0.52, impact: 0.26, lagDays: 30, note: "Product cargo competition for regional tenders" },
        ],
      },
      {
        channel: "trade",
        direction: "escalatory",
        magnitude: 0.42,
        lagDays: [20, 70],
        confidence: 0.66,
        mechanism: "Import substitution and freight cost compound into landed product prices with a lag set by contract structure.",
        exposures: [
          { nodeId: "IN", exposure: 0.64, impact: 0.33, lagDays: 35, note: "Landed-cost inflation on product imports" },
          { nodeId: "US", exposure: 0.46, impact: 0.22, lagDays: 40, note: "Export cargo availability improves" },
        ],
      },
      {
        channel: "finance",
        direction: "mixed",
        magnitude: 0.36,
        lagDays: [10, 40],
        confidence: 0.62,
        mechanism: "Crack-driven earnings dispersion rather than index-level impact.",
        exposures: [
          { nodeId: "INSTL", exposure: 0.4, impact: 0.17, lagDays: 20, note: "Refining versus integrated earnings dispersion" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "mixed",
        magnitude: 0.31,
        lagDays: [40, 130],
        confidence: 0.52,
        mechanism: "Sourcing arrangements are commercial and rarely need state involvement.",
        exposures: [
          { nodeId: "IN", exposure: 0.42, impact: 0.17, lagDays: 60, note: "Bilateral sourcing terms negotiated" },
        ],
      },
    ],
  },
];