import type { Scenario } from "./types";

/** Scenario corpus, part 1 of 3 — technology and critical minerals. */
export const SCENARIOS_1: Scenario[] = [
  {
    id: "MER-4117",
    reference: "TRD/SEMI/04",
    title: "Export-control consolidation on advanced semiconductor tooling",
    summary:
      "Three allied jurisdictions have moved within a six-week window to align licensing requirements for EUV, high-NA DUV and advanced metrology tools, closing the third-country routing route that suppliers used through unlisted intermediaries.",
    stage: "escalating",
    detectedAt: "2026-09-28",
    firstSignalAt: "2026-09-11",
    confidence: 0.83,
    novelty: 0.91,
    velocity: 0.78,
    actors: ["US", "NL", "JP", "KR", "CN", "TW"],
    regions: ["East Asia", "Europe"],
    tags: ["export controls", "semiconductors", "industrial policy"],
    analystNote:
      "The cross-jurisdictional timing is the signal, not any single rule. Aligning three licensing regimes inside six weeks removes the re-routing arbitrage that made prior controls porous.",
    tailScenario:
      "A contested interpretation of 'advanced metrology' splits the coalition. Two suppliers resume non-compliant shipments via a bonded warehouse in a third jurisdiction, and an ally publicly declines to align, exposing the enforcement perimeter.",
    signals: [
      {
        id: "S-4117-1",
        source: "Netherlands Ministry of Economic Affairs",
        sourceClass: "official",
        observedAt: "2026-09-11",
        channel: "trade",
        headline: "Licensing regime extended to two additional tool classes",
        detail:
          "Administrative extension published with a 45-day comment window covering high-NA DUV and a defined band of metrology tooling.",
        reliability: 0.97,
        weight: 0.92,
        corroborations: 6,
        anomalyZ: 3.4,
      },
      {
        id: "S-4117-2",
        source: "US Bureau of Industry and Security",
        sourceClass: "official",
        observedAt: "2026-09-19",
        channel: "diplomatic",
        headline: "Rulemaking docket opened on end-use verification",
        detail:
          "Docket proposes mandatory downstream end-use attestation for all non-US persons transacting covered tools, including via distributors.",
        reliability: 0.96,
        weight: 0.88,
        corroborations: 4,
        anomalyZ: 2.9,
      },
      {
        id: "S-4117-3",
        source: "Reuters wire",
        sourceClass: "wire",
        observedAt: "2026-09-24",
        channel: "trade",
        headline: "Japanese subsidy conditions redrafted around tool origin",
        detail:
          "Revised allocation requires domestic origination of covered tool sub-components, effective next fiscal year.",
        reliability: 0.88,
        weight: 0.7,
        corroborations: 3,
        anomalyZ: 2.1,
      },
      {
        id: "S-4117-4",
        source: "Memory pricing desk, Seoul",
        sourceClass: "market",
        observedAt: "2026-09-30",
        channel: "finance",
        headline: "DRAM contract prices deviate 2.8 sigma from 90-day baseline",
        detail:
          "Contract and spot prices for advanced DRAM diverge sharply, consistent with inventory withholding ahead of a licensing cutoff.",
        reliability: 0.82,
        weight: 0.74,
        corroborations: 5,
        anomalyZ: 2.8,
      },
      {
        id: "S-4117-5",
        source: "Open-source shipping manifests aggregator",
        sourceClass: "social",
        observedAt: "2026-10-01",
        channel: "trade",
        headline: "Air freight of tool spares up 340% week-on-week",
        detail:
          "Spares and service units, not production tools, account for most of the increase — consistent with a grandfathering deadline.",
        reliability: 0.44,
        weight: 0.36,
        corroborations: 1,
        anomalyZ: 3.9,
      },
    ],
    pathways: [
      {
        channel: "trade",
        direction: "escalatory",
        magnitude: 0.88,
        lagDays: [21, 55],
        confidence: 0.86,
        mechanism:
          "Tool-level denial propagates forward along the semiconductor bill-of-materials: advanced logic capacity first, then memory pricing, then assembly. Re-routing adds 25–45 days of lead time, which front-loads the shock into inventory rather than output.",
        exposures: [
          { nodeId: "TW", exposure: 0.94, impact: 0.61, lagDays: 34, note: "Leading-edge logic expansion programmes re-sequenced" },
          { nodeId: "KR", exposure: 0.81, impact: 0.44, lagDays: 28, note: "DRAM capital plans shifted to mature nodes" },
          { nodeId: "CN", exposure: 0.72, impact: 0.57, lagDays: 40, note: "Tool service and spares access narrows first" },
          { nodeId: "JP", exposure: 0.66, impact: 0.31, lagDays: 30, note: "Materials suppliers see order deferral" },
          { nodeId: "NL", exposure: 0.58, impact: 0.52, lagDays: 21, note: "Export-licence throughput becomes a binding constraint" },
          { nodeId: "SG", exposure: 0.55, impact: 0.29, lagDays: 45, note: "Transshipment scrutiny raises dwell time" },
        ],
      },
      {
        channel: "finance",
        direction: "escalatory",
        magnitude: 0.51,
        lagDays: [5, 20],
        confidence: 0.71,
        mechanism:
          "Two-stage repricing: memory spot contracts move first, then foundry-weighted equity multiples. Institutional positioning in the supply chain concentrates the drawdown.",
        exposures: [
          { nodeId: "INSTL", exposure: 0.72, impact: 0.34, lagDays: 9, note: "Supply-chain equity concentration cuts" },
          { nodeId: "KR", exposure: 0.63, impact: 0.38, lagDays: 12, note: "Memory names lead sector de-rating" },
          { nodeId: "TW", exposure: 0.6, impact: 0.31, lagDays: 10, note: "Foundry multiple compresses on capex risk" },
          { nodeId: "SWIFT", exposure: 0.3, impact: 0.12, lagDays: 15, note: "Settlement friction limited to flagged corridors" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "mixed",
        magnitude: 0.47,
        lagDays: [10, 40],
        confidence: 0.63,
        mechanism:
          "Allied coordination is the mechanism of the control itself, which makes it self-reinforcing for allies and openly contested by the target. Retaliatory consultation requests raise the floor without changing the ceiling.",
        exposures: [
          { nodeId: "CN", exposure: 0.68, impact: 0.46, lagDays: 18, note: "Consultation requests filed; export-control retaliation threatened" },
          { nodeId: "US", exposure: 0.55, impact: 0.27, lagDays: 14, note: "Coalition cohesion becomes a stated policy goal" },
          { nodeId: "NL", exposure: 0.5, impact: 0.24, lagDays: 20, note: "Domestic industry pushback on licence volume" },
          { nodeId: "EU", exposure: 0.44, impact: 0.22, lagDays: 25, note: "Member-state split on economic cost" },
        ],
      },
      {
        channel: "energy",
        direction: "mixed",
        magnitude: 0.22,
        lagDays: [45, 110],
        confidence: 0.44,
        mechanism:
          "Weak and lagged. Only via fab electricity contracts and the industrial-power queue, where new capacity is already deferred rather than cancelled.",
        exposures: [
          { nodeId: "TW", exposure: 0.3, impact: 0.14, lagDays: 70, note: "Industrial load forecast revised marginally down" },
          { nodeId: "JP", exposure: 0.26, impact: 0.11, lagDays: 85, note: "Grid connection queue slippage" },
        ],
      },
    ],
  },
  {
    id: "MER-4170",
    reference: "TRD/MIN/02",
    title: "Rare-earth licensing regime extended to two further material classes",
    summary:
      "Export licensing requirements have been extended from separation and polishing inputs to magnet-grade alloys and heavy rare-earth targets, capturing the value-add step rather than the ore step.",
    stage: "emerging",
    detectedAt: "2026-09-26",
    firstSignalAt: "2026-09-15",
    confidence: 0.71,
    novelty: 0.86,
    velocity: 0.61,
    actors: ["CN", "JP", "DE", "US", "EU"],
    regions: ["East Asia", "Europe"],
    tags: ["critical minerals", "export controls"],
    analystNote:
      "Regulatory scope that stops at ore is a tariff. Scope that reaches alloy and magnet-grade material is a chokepoint. The distinction is the whole risk here.",
    tailScenario:
      "Downstream magnet producers pre-buy twelve months of inventory, then the licensing authority tightens approval throughput rather than eligibility. Exhaustion of the pre-buy inventory coincides with a production halt in a single magnet cluster.",
    signals: [
      {
        id: "S-4170-1",
        source: "State Council export control catalogue amendment",
        sourceClass: "official",
        observedAt: "2026-09-15",
        channel: "trade",
        headline: "Magnet-grade alloys and heavy RE targets added to controlled catalogue",
        detail: "Annex published covering dysprosium, terbium and neodymium magnet alloys at defined purity bands.",
        reliability: 0.95,
        weight: 0.9,
        corroborations: 5,
        anomalyZ: 3.1,
      },
      {
        id: "S-4170-2",
        source: "European automotive supply chain survey",
        sourceClass: "intel",
        observedAt: "2026-09-22",
        channel: "trade",
        headline: "Magnet makers report doubled lead times on qualifying stock",
        detail: "Qualification of an alternative origin takes 9–14 months, so lead-time extension is effectively a binding constraint.",
        reliability: 0.76,
        weight: 0.72,
        corroborations: 3,
        anomalyZ: 2.3,
      },
      {
        id: "S-4170-3",
        source: "Tokyo commodity desk",
        sourceClass: "market",
        observedAt: "2026-09-29",
        channel: "finance",
        headline: "Dysprosium oxide premium widens to a 14-month high",
        detail: "Physical premium expansion outpacing benchmark contract moves.",
        reliability: 0.8,
        weight: 0.66,
        corroborations: 4,
        anomalyZ: 2.4,
      },
      {
        id: "S-4170-4",
        source: "Trade ministry spokesperson briefing",
        sourceClass: "official",
        observedAt: "2026-10-01",
        channel: "diplomatic",
        headline: "Objection lodged at the WTO committee",
        detail: "Objection framed as a non-discrimination failure; procedural, with no suspension request.",
        reliability: 0.86,
        weight: 0.44,
        corroborations: 2,
        anomalyZ: 1.4,
      },
    ],
    pathways: [
      {
        channel: "trade",
        direction: "escalatory",
        magnitude: 0.79,
        lagDays: [30, 90],
        confidence: 0.79,
        mechanism:
          "Control at the alloy stage removes the substitution route. Downstream users cannot re-source quickly because alternative origins require 9–14 months of qualification, so effective elasticity of demand is near zero inside one planning cycle.",
        exposures: [
          { nodeId: "DE", exposure: 0.88, impact: 0.52, lagDays: 60, note: "Traction motor and actuator supply contracted on long-term offtake" },
          { nodeId: "JP", exposure: 0.82, impact: 0.47, lagDays: 55, note: "Servo motor and HDD actuator exposure" },
          { nodeId: "US", exposure: 0.7, impact: 0.38, lagDays: 50, note: "Defence-contract magnet qualification backlog" },
          { nodeId: "EU", exposure: 0.68, impact: 0.36, lagDays: 65, note: "Aggregate member-state exposure via automotive tiering" },
          { nodeId: "CN", exposure: 0.6, impact: 0.24, lagDays: 20, note: "Upstream value capture intact; downstream margin shifts" },
        ],
      },
      {
        channel: "finance",
        direction: "escalatory",
        magnitude: 0.44,
        lagDays: [8, 30],
        confidence: 0.68,
        mechanism:
          "Physical premium and equity re-rating move together for upstream holders; downstream users carry the cost without a hedge, so dispersion widens before index-level damage appears.",
        exposures: [
          { nodeId: "INSTL", exposure: 0.58, impact: 0.26, lagDays: 14, note: "Materials overweight versus downstream underweight" },
          { nodeId: "DE", exposure: 0.5, impact: 0.24, lagDays: 18, note: "Downstream margin guidance at risk" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "mixed",
        magnitude: 0.49,
        lagDays: [20, 75],
        confidence: 0.66,
        mechanism:
          "Procedural objections preserve an off-ramp but consume the time advantage that made the regime effective. Each month of WTO process is a month of inventory accumulation by the exposed side.",
        exposures: [
          { nodeId: "EU", exposure: 0.55, impact: 0.28, lagDays: 30, note: "Coordination between exposed members" },
          { nodeId: "CN", exposure: 0.5, impact: 0.21, lagDays: 25, note: "Retaliatory catalogue language signalled" },
          { nodeId: "US", exposure: 0.46, impact: 0.19, lagDays: 22, note: "Allied pre-emption of alternative supply investment" },
        ],
      },
      {
        channel: "energy",
        direction: "mixed",
        magnitude: 0.24,
        lagDays: [70, 160],
        confidence: 0.38,
        mechanism:
          "Lagged and indirect through EV and wind-turbine production volume rather than mineral prices.",
        exposures: [
          { nodeId: "DE", exposure: 0.26, impact: 0.12, lagDays: 110, note: "EV production-plan slippage" },
        ],
      },
    ],
  },
  {
    id: "MER-4122",
    reference: "TRD/SHP/07",
    title: "Bab el-Mandeb interdiction extended to transiting tankers",
    summary:
      "Interdiction activity has moved from container and bulk carriers to crude and product tankers, extending the affected commodity set and the insurers willing to underwrite the corridor.",
    stage: "active",
    detectedAt: "2026-09-21",
    firstSignalAt: "2026-08-30",
    confidence: 0.88,
    novelty: 0.62,
    velocity: 0.72,
    actors: ["EU", "US", "SA", "AE", "IN", "EG"],
    regions: ["East Africa", "Middle East", "South Asia"],
    tags: ["maritime security", "shipping", "insurance"],
    analystNote:
      "The escalation that matters is the shift from physical interception to underwriter withdrawal. Once the P&I market prices the corridor as uninsurable, interdiction becomes a price phenomenon rather than a security one.",
    tailScenario:
      "A product-tanker hit in international waters triggers a collective response, but response latency exceeds the seven-day insurance-renewal cycle. Coverage is withdrawn first; the physical escalation follows the coverage, not the reverse.",
    signals: [
      {
        id: "S-4122-1",
        source: "Lloyd's market bulletin",
        sourceClass: "market",
        observedAt: "2026-08-30",
        channel: "finance",
        headline: "War-risk premia for Gulf–Europe crude rise fourfold",
        detail: "Premium repricing applies to hulls with no credible rerouting option in the current charter window.",
        reliability: 0.9,
        weight: 0.82,
        corroborations: 7,
        anomalyZ: 3.6,
      },
      {
        id: "S-4122-2",
        source: "UKMTO advisory",
        sourceClass: "official",
        observedAt: "2026-09-04",
        channel: "trade",
        headline: "Transit guidance lowered to product and crude tankers",
        detail: "Advisory extends caution from general navigation to a named vessel class across a wider latitudinal band.",
        reliability: 0.94,
        weight: 0.86,
        corroborations: 5,
        anomalyZ: 3.2,
      },
      {
        id: "S-4122-3",
        source: "Reuters wire",
        sourceClass: "wire",
        observedAt: "2026-09-12",
        channel: "trade",
        headline: "Two tankers reroute via Cape, adding 11–14 days",
        detail: "Chartering reports indicate the reroute is priced into freight rather than resisted by operators.",
        reliability: 0.87,
        weight: 0.74,
        corroborations: 6,
        anomalyZ: 2.7,
      },
      {
        id: "S-4122-4",
        source: "Athens ship-spot desk",
        sourceClass: "market",
        observedAt: "2026-09-21",
        channel: "energy",
        headline: "VLCC tonne-miles up 22% while global loadings flat",
        detail: "The gap between tonne-miles and volumes is the cleanest available measure of the security premium.",
        reliability: 0.85,
        weight: 0.8,
        corroborations: 4,
        anomalyZ: 3.1,
      },
      {
        id: "S-4122-5",
        source: "Regional diplomatic readout",
        sourceClass: "official",
        observedAt: "2026-09-27",
        channel: "diplomatic",
        headline: "Transit-notification mechanism invoked for first time",
        detail: "Pre-notification framework activated between adjacent states, indicating a move from reactive to managed corridor governance.",
        reliability: 0.79,
        weight: 0.52,
        corroborations: 3,
        anomalyZ: 1.8,
      },
    ],
    pathways: [
      {
        channel: "energy",
        direction: "escalatory",
        magnitude: 0.84,
        lagDays: [10, 40],
        confidence: 0.85,
        mechanism:
          "Distance, not volume, sets the price. Additional tonne-miles on a fixed tanker fleet are arithmetically equivalent to supply loss, and the elasticity of substitution toward alternative origin is low inside a quarter.",
        exposures: [
          { nodeId: "EU", exposure: 0.86, impact: 0.58, lagDays: 21, note: "Refinery crude slate discount to alternative origins" },
          { nodeId: "IN", exposure: 0.79, impact: 0.51, lagDays: 24, note: "Refinery margin compression on long-haul imports" },
          { nodeId: "SA", exposure: 0.6, impact: 0.33, lagDays: 18, note: "Export revenue protected, loadings redirected" },
          { nodeId: "AE", exposure: 0.64, impact: 0.38, lagDays: 20, note: "Storage utilisation elevated on reroute anticipation" },
        ],
      },
      {
        channel: "trade",
        direction: "escalatory",
        magnitude: 0.72,
        lagDays: [14, 45],
        confidence: 0.81,
        mechanism:
          "Freight cost enters landed price directly, and schedule unreliability compounds it. Container lines absorb the first tranche; the pass-through to goods prices arrives at the second.",
        exposures: [
          { nodeId: "EU", exposure: 0.78, impact: 0.49, lagDays: 30, note: "Landed-cost inflation in import-dependent categories" },
          { nodeId: "IN", exposure: 0.7, impact: 0.42, lagDays: 28, note: "Export competitiveness erosion on long-haul routes" },
          { nodeId: "AE", exposure: 0.58, impact: 0.3, lagDays: 26, note: "Transhipment and warehousing demand rises" },
          { nodeId: "REDSEA", exposure: 0.92, impact: 0.61, lagDays: 15, note: "Chokepoint throughput is the origin of the shock" },
        ],
      },
      {
        channel: "finance",
        direction: "escalatory",
        magnitude: 0.66,
        lagDays: [4, 18],
        confidence: 0.78,
        mechanism:
          "Insurance is the fastest channel because it reprices on renewal rather than on delivery. Credit spreads on exposed sovereigns follow within weeks.",
        exposures: [
          { nodeId: "INSTL", exposure: 0.7, impact: 0.38, lagDays: 8, note: "Commodity and shipping factor concentration" },
          { nodeId: "SWIFT", exposure: 0.4, impact: 0.19, lagDays: 12, note: "Trade-finance pricing on flagged voyages" },
          { nodeId: "EU", exposure: 0.46, impact: 0.23, lagDays: 15, note: "Corporate credit repricing for import-intensive sectors" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "mixed",
        magnitude: 0.58,
        lagDays: [25, 90],
        confidence: 0.64,
        mechanism:
          "The notification mechanism is evidence of partial governance, which lowers tail probability while raising coordination cost. It is a partial off-ramp, not a resolution.",
        exposures: [
          { nodeId: "EG", exposure: 0.55, impact: 0.31, lagDays: 35, note: "Corridor governance dependent on transit state" },
          { nodeId: "EU", exposure: 0.48, impact: 0.24, lagDays: 40, note: "Mandate renewal becomes the binding constraint" },
          { nodeId: "SA", exposure: 0.44, impact: 0.2, lagDays: 45, note: "Bilateral arrangements outside the multilateral frame" },
        ],
      },
    ],
  },
  {
    id: "MER-4130",
    reference: "NRG/HZM/03",
    title: "Convoy incident and escort posture change in the Strait of Hormuz",
    summary:
      "A tanker convoy proceeding under naval escort has come under contact, producing a change in escort posture from transit support to route-avoidance advice for several majors.",
    stage: "escalating",
    detectedAt: "2026-10-02",
    firstSignalAt: "2026-09-18",
    confidence: 0.79,
    novelty: 0.84,
    velocity: 0.86,
    actors: ["IR", "US", "GB", "AE", "SA", "CN", "IN"],
    regions: ["Middle East", "South Asia"],
    tags: ["chokepoint", "energy security", "naval posture"],
    analystNote:
      "Hormuz is the one node in the graph where a single incident can reprice the entire energy complex within a trading session. Treat any change in escort doctrine as a first-order signal, not a detail.",
    tailScenario:
      "A mine or drone strike on a major produces sustained closure of the western approaches. With no meaningful bypass pipeline capacity, the model's energy coefficient dominates the composite and the 30-day interval upper bound becomes the operative number.",
    signals: [
      {
        id: "S-4130-1",
        source: "Combined maritime advisory",
        sourceClass: "official",
        observedAt: "2026-09-18",
        channel: "energy",
        headline: "Posture shifted from escort to route-avoidance advice",
        detail: "Advisory language changed from 'transit support available' to 'consider alternative routing', a discrete doctrinal change.",
        reliability: 0.93,
        weight: 0.9,
        corroborations: 5,
        anomalyZ: 3.5,
      },
      {
        id: "S-4130-2",
        source: "Reuters wire",
        sourceClass: "wire",
        observedAt: "2026-09-23",
        channel: "energy",
        headline: "Contact reported between escort group and fast-craft group",
        detail: "Reports describe a standoff rather than an exchange, with damage disputed across sources.",
        reliability: 0.79,
        weight: 0.74,
        corroborations: 4,
        anomalyZ: 2.9,
      },
      {
        id: "S-4130-3",
        source: "Singapore bunkering desk",
        sourceClass: "market",
        observedAt: "2026-09-25",
        channel: "finance",
        headline: "Front-month crude skew flattens on prompt-supply bid",
        detail: "Backwardation narrowing is the market's way of pricing a supply expectation rather than a demand one.",
        reliability: 0.85,
        weight: 0.72,
        corroborations: 4,
        anomalyZ: 2.5,
      },
      {
        id: "S-4130-4",
        source: "Gulf state foreign ministry statement",
        sourceClass: "official",
        observedAt: "2026-09-29",
        channel: "diplomatic",
        headline: "Contact urged through a third-country channel",
        detail: "Deliberate third-country intermediation implies neither side wants a direct bilateral record.",
        reliability: 0.88,
        weight: 0.58,
        corroborations: 3,
        anomalyZ: 2.0,
      },
      {
        id: "S-4130-5",
        source: "Tanker AIS analytics provider",
        sourceClass: "intel",
        observedAt: "2026-10-02",
        channel: "trade",
        headline: "Transits down 9% against seasonal baseline",
        detail: "Transit shortfall measured against a five-year seasonal profile rather than the prior week.",
        reliability: 0.81,
        weight: 0.76,
        corroborations: 3,
        anomalyZ: 3.3,
      },
    ],
    pathways: [
      {
        channel: "energy",
        direction: "escalatory",
        magnitude: 0.93,
        lagDays: [2, 21],
        confidence: 0.87,
        mechanism:
          "Bypass pipeline capacity is a small fraction of normal strait throughput, so effective supply is near-binary. This channel dominates any composite that contains it, which is why the engine weights energy above the others.",
        exposures: [
          { nodeId: "HORMUZ", exposure: 0.99, impact: 0.78, lagDays: 3, note: "Origin of the shock; no meaningful bypass capacity" },
          { nodeId: "IN", exposure: 0.88, impact: 0.72, lagDays: 10, note: "Import dependence with limited strategic reserve" },
          { nodeId: "CN", exposure: 0.84, impact: 0.63, lagDays: 12, note: "Discounted crude origin concentration" },
          { nodeId: "JP", exposure: 0.82, impact: 0.61, lagDays: 9, note: "Almost total import dependence" },
          { nodeId: "KR", exposure: 0.8, impact: 0.58, lagDays: 9, note: "Refinery configuration optimised to Middle East slate" },
          { nodeId: "EU", exposure: 0.62, impact: 0.44, lagDays: 14, note: "Partial offset from non-Gulf sourcing" },
        ],
      },
      {
        channel: "finance",
        direction: "escalatory",
        magnitude: 0.7,
        lagDays: [1, 10],
        confidence: 0.8,
        mechanism:
          "Fastest transmission in the model. Energy derivatives reprice intraday; inflation expectations and currency follow within sessions.",
        exposures: [
          { nodeId: "INSTL", exposure: 0.76, impact: 0.46, lagDays: 3, note: "Commodity beta and inflation breakeven repricing" },
          { nodeId: "SWIFT", exposure: 0.45, impact: 0.24, lagDays: 6, note: "Payment behaviour shifts toward precautionary buffers" },
          { nodeId: "IN", exposure: 0.52, impact: 0.29, lagDays: 5, note: "External balance and FX channel" },
        ],
      },
      {
        channel: "trade",
        direction: "escalatory",
        magnitude: 0.6,
        lagDays: [7, 35],
        confidence: 0.72,
        mechanism:
          "Freight and insurance compound the commodity shock, then the composite lands on landed goods prices with a lag set by contract structure.",
        exposures: [
          { nodeId: "AE", exposure: 0.72, impact: 0.42, lagDays: 12, note: "Re-export hub throughput exposed" },
          { nodeId: "SA", exposure: 0.62, impact: 0.33, lagDays: 10, note: "Loading programme schedules, not volumes, are hit" },
          { nodeId: "IN", exposure: 0.6, impact: 0.36, lagDays: 20, note: "Landed-cost inflation on essential imports" },
          { nodeId: "SUZK", exposure: 0.4, impact: 0.2, lagDays: 22, note: "Canal economics pressured by fleet repositioning" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "escalatory",
        magnitude: 0.71,
        lagDays: [5, 45],
        confidence: 0.7,
        mechanism:
          "Escort doctrine is a negotiated artefact. Every posture change raises the probability that the next one is ratcheted rather than reversed.",
        exposures: [
          { nodeId: "IR", exposure: 0.78, impact: 0.49, lagDays: 15, note: "Leverage calculus shifts toward pre-emption" },
          { nodeId: "US", exposure: 0.7, impact: 0.41, lagDays: 18, note: "Allied consultation requirements slow response" },
          { nodeId: "GB", exposure: 0.6, impact: 0.33, lagDays: 16, note: "Inherited posture with limited domestic mandate" },
          { nodeId: "AE", exposure: 0.5, impact: 0.26, lagDays: 20, note: "Mediation role becomes more valuable and more exposed" },
        ],
      },
    ],
  },
];