import type { Scenario } from "./types";

/** Scenario corpus, part 2 of 3 — finance and corridors. */
export const SCENARIOS_2: Scenario[] = [
  {
    id: "MER-4135",
    reference: "FIN/SAN/05",
    title: "Sanctions circumvention network resolved through a re-export corridor",
    summary:
      "An enforcement action has identified a three-node re-export chain that moved controlled components through a bonded corridor, with the corridor state simultaneously seeking relief from a separate measure.",
    stage: "active",
    detectedAt: "2026-09-24",
    firstSignalAt: "2026-09-02",
    confidence: 0.81,
    novelty: 0.74,
    velocity: 0.68,
    actors: ["US", "EU", "TR", "AE", "CN", "SG", "NL"],
    regions: ["Eurasia", "Middle East", "Asia-Pacific"],
    tags: ["sanctions", "enforcement", "trade finance"],
    analystNote:
      "Enforcement has shifted from listing entities to reconstructing the transaction chain. The corridor state is now the pivot: it is simultaneously the most exposed and the most motivated negotiator.",
    tailScenario:
      "A negotiated carve-out for the corridor state is traded for cooperation on the evasion chain. The evasion network survives in a modified form, but the precedent that corridor states can buy relief transfers the centre of gravity to intermediaries.",
    signals: [
      {
        id: "S-4135-1",
        source: "Enforcement agency designation notice",
        sourceClass: "official",
        observedAt: "2026-09-02",
        channel: "finance",
        headline: "Designation rests on reconstructed transaction chain",
        detail: "Evidentiary basis is a chain of 41 shipments, not beneficial ownership of a single entity.",
        reliability: 0.94,
        weight: 0.88,
        corroborations: 5,
        anomalyZ: 3.0,
      },
      {
        id: "S-4135-2",
        source: "Reuters wire",
        sourceClass: "wire",
        observedAt: "2026-09-09",
        channel: "trade",
        headline: "Bonded warehousing facility placed under enhanced supervision",
        detail: "Customs supervision escalates to continuous audit at a transshipment node used by both evasion routes.",
        reliability: 0.86,
        weight: 0.7,
        corroborations: 4,
        anomalyZ: 2.6,
      },
      {
        id: "S-4135-3",
        source: "Corridor state finance ministry briefing",
        sourceClass: "official",
        observedAt: "2026-09-17",
        channel: "diplomatic",
        headline: "Relief from a separate measure requested as consideration",
        detail: "Explicit linkage of two previously unrelated files signals a bargaining posture rather than a legal position.",
        reliability: 0.85,
        weight: 0.66,
        corroborations: 3,
        anomalyZ: 2.4,
      },
      {
        id: "S-4135-4",
        source: "Trade finance desk, Istanbul",
        sourceClass: "market",
        observedAt: "2026-09-24",
        channel: "finance",
        headline: "Compliance cost on flagged corridors widens to 4.1% of face value",
        detail: "Bank pricing for enhanced due diligence on affected corridors rises faster than compliance staffing.",
        reliability: 0.83,
        weight: 0.62,
        corroborations: 4,
        anomalyZ: 2.2,
      },
    ],
    pathways: [
      {
        channel: "finance",
        direction: "escalatory",
        magnitude: 0.76,
        lagDays: [7, 40],
        confidence: 0.79,
        mechanism:
          "Correspondent banking de-risks ahead of legal obligation. Once pricing moves, the commercial channel enforces the policy more strictly than the legal one — and it moves first.",
        exposures: [
          { nodeId: "SWIFT", exposure: 0.82, impact: 0.54, lagDays: 12, note: "Correspondent relationships restructured on flagged corridors" },
          { nodeId: "TR", exposure: 0.78, impact: 0.52, lagDays: 20, note: "Payment volumes diverted; domestic cost absorbed" },
          { nodeId: "AE", exposure: 0.74, impact: 0.47, lagDays: 22, note: "Re-export hub volumes fall before rules change" },
          { nodeId: "SG", exposure: 0.68, impact: 0.4, lagDays: 18, note: "Regional hub compliance premium" },
          { nodeId: "INSTL", exposure: 0.5, impact: 0.24, lagDays: 25, note: "Emerging-market credit differentiation" },
        ],
      },
      {
        channel: "trade",
        direction: "escalatory",
        magnitude: 0.64,
        lagDays: [20, 60],
        confidence: 0.72,
        mechanism:
          "Enforcement at one node raises inspection rates at adjacent nodes, which raises effective transit time for compliant cargo travelling the same corridors.",
        exposures: [
          { nodeId: "TR", exposure: 0.72, impact: 0.45, lagDays: 28, note: "Transit time inflation for compliant traffic" },
          { nodeId: "AE", exposure: 0.66, impact: 0.38, lagDays: 30, note: "Warehousing demand substitutes for re-export" },
          { nodeId: "NL", exposure: 0.5, impact: 0.26, lagDays: 24, note: "Distribution node adds end-use attestation" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "mixed",
        magnitude: 0.68,
        lagDays: [20, 80],
        confidence: 0.7,
        mechanism:
          "The corridor state's bargaining move creates a template other intermediaries will attempt. Leverage rises for states with routing utility and falls for states without.",
        exposures: [
          { nodeId: "TR", exposure: 0.72, impact: 0.44, lagDays: 30, note: "Pivot state gains leverage and exposure together" },
          { nodeId: "EU", exposure: 0.55, impact: 0.29, lagDays: 35, note: "Relief precedents fragment the coalition" },
          { nodeId: "US", exposure: 0.58, impact: 0.31, lagDays: 28, note: "Enforcement coherence under pressure" },
        ],
      },
      // A channel that was assessed and ruled out.
      //
      // This pathway reaches no node, which is the point: component-level
      // enforcement does not touch hydrocarbon flows. It is kept because the
      // reasoning is part of the record, and it carries magnitude 0 so the
      // authored figure agrees with the mechanism above it. A non-zero figure
      // here used to feed the composite — energy carries the largest weight of
      // the four channels — so the event scored as though it transmitted on
      // energy while exposing nothing on it. `channelPressureOf` now ignores a
      // pathway that exposes no node for the same reason, so this cannot recur.
      {
        channel: "energy",
        direction: "mixed",
        magnitude: 0,
        lagDays: [90, 200],
        confidence: 0.31,
        mechanism: "Negligible. Component-level enforcement does not touch hydrocarbon flows.",
        exposures: [],
      },
    ],
  },
  {
    id: "MER-4141",
    reference: "FIN/TW/02",
    title: "Live-fire exercise window declared in the Taiwan Strait",
    summary:
      "A multi-day exercise window has been declared covering live-fire and amphibious elements, announced outside any previously announced calendar and overlapping a shipping conference.",
    stage: "emerging",
    detectedAt: "2026-09-30",
    firstSignalAt: "2026-09-20",
    confidence: 0.75,
    novelty: 0.93,
    velocity: 0.69,
    actors: ["CN", "TW", "US", "JP", "SG", "EU"],
    regions: ["East Asia", "Asia-Pacific"],
    tags: ["exercise window", "chokepoint", "semiconductors"],
    analystNote:
      "Novelty is driven by the calendar break, not the exercise itself. Exercises are routine; unannounced timing is the observable that historically carries information.",
    tailScenario:
      "The window extends without a start date, and commercial carriers withdraw from adjacent air and sea lanes on precautionary grounds. The economic impact is driven by voluntary commercial retreat rather than by any instructed closure.",
    signals: [
      {
        id: "S-4141-1",
        source: "Maritime safety administration notice",
        sourceClass: "official",
        observedAt: "2026-09-20",
        channel: "trade",
        headline: "Exercise area declared outside the published calendar",
        detail: "Declaration cites 'unannounced elements', which is a category of first resort in published notices.",
        reliability: 0.9,
        weight: 0.84,
        corroborations: 4,
        anomalyZ: 3.3,
      },
      {
        id: "S-4141-2",
        source: "Airline scheduling data",
        sourceClass: "market",
        observedAt: "2026-09-23",
        channel: "trade",
        headline: "Regional carrier capacity withdrawn from four rotations",
        detail: "Retirements are commercial and immediate; the carriers do not cite a security justification.",
        reliability: 0.84,
        weight: 0.7,
        corroborations: 3,
        anomalyZ: 2.6,
      },
      {
        id: "S-4141-3",
        source: "Semiconductor foundry supply-chain desk",
        sourceClass: "intel",
        observedAt: "2026-09-26",
        channel: "trade",
        headline: "Customers request buffer stock above standard safety stock",
        detail: "Buffer-stock requests cluster among European and North American buyers rather than regionally biased ones.",
        reliability: 0.78,
        weight: 0.62,
        corroborations: 3,
        anomalyZ: 2.2,
      },
      {
        id: "S-4141-4",
        source: "Ministry of defence statement",
        sourceClass: "official",
        observedAt: "2026-09-30",
        channel: "diplomatic",
        headline: "Presence affirmed, no date specified",
        detail: "Deliberate ambiguity: presence is confirmed, timing is not, which is the ambiguity that moves prices.",
        reliability: 0.89,
        weight: 0.6,
        corroborations: 4,
        anomalyZ: 2.4,
      },
    ],
    pathways: [
      {
        channel: "trade",
        direction: "escalatory",
        magnitude: 0.71,
        lagDays: [7, 45],
        confidence: 0.74,
        mechanism:
          "Voluntary commercial retreat is the transmission mechanism. Carriers and customers act on perceived risk before any official restriction, so trade volume moves without a rule changing.",
        exposures: [
          { nodeId: "TAIWANSTR", exposure: 0.96, impact: 0.6, lagDays: 10, note: "Declared area sits on the primary east-west lane" },
          { nodeId: "TW", exposure: 0.9, impact: 0.62, lagDays: 14, note: "Buffer-stock build by offshore customers" },
          { nodeId: "JP", exposure: 0.68, impact: 0.36, lagDays: 18, note: "Southern service rotations cut" },
          { nodeId: "SG", exposure: 0.62, impact: 0.33, lagDays: 20, note: "Transhipment bookings re-routed" },
          { nodeId: "KR", exposure: 0.6, impact: 0.28, lagDays: 20, note: "Air cargo capacity absorbed" },
        ],
      },
      {
        channel: "finance",
        direction: "escalatory",
        magnitude: 0.73,
        lagDays: [1, 14],
        confidence: 0.78,
        mechanism:
          "Tail-risk pricing dominates: options skew, not spot prices. The market is pricing the exercise window's tail, so dispersion rises before any index moves materially.",
        exposures: [
          { nodeId: "INSTL", exposure: 0.7, impact: 0.4, lagDays: 4, note: "Equity skew and volatility term structure steepen" },
          { nodeId: "TW", exposure: 0.66, impact: 0.38, lagDays: 5, note: "Index discount to peers widens" },
          { nodeId: "CN", exposure: 0.5, impact: 0.24, lagDays: 6, note: "Defensive sector rotation" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "escalatory",
        magnitude: 0.61,
        lagDays: [3, 30],
        confidence: 0.72,
        mechanism:
          "Ambiguity is the escalation currency. Neither side can de-escalate a window that has no stated end, so the risk accumulates in the ambiguity itself.",
        exposures: [
          { nodeId: "CN", exposure: 0.7, impact: 0.38, lagDays: 12, note: "Framing shifts from exercise to readiness verification" },
          { nodeId: "US", exposure: 0.62, impact: 0.32, lagDays: 10, note: "Positioning decisions become the observable" },
          { nodeId: "JP", exposure: 0.52, impact: 0.25, lagDays: 15, note: "Domestic political constraint on involvement" },
          { nodeId: "EU", exposure: 0.42, impact: 0.19, lagDays: 18, note: "Economic exposure acknowledged without a position" },
        ],
      },
      {
        channel: "energy",
        direction: "mixed",
        magnitude: 0.31,
        lagDays: [45, 120],
        confidence: 0.44,
        mechanism:
          "LNG spot sourcing is the only meaningful link. Spot-buyer concentration in Northeast Asia makes short-run substitution imperfect.",
        exposures: [
          { nodeId: "JP", exposure: 0.45, impact: 0.24, lagDays: 60, note: "Spot LNG sourcing premium" },
          { nodeId: "KR", exposure: 0.4, impact: 0.21, lagDays: 62, note: "Winter procurement mix shifted to term" },
        ],
      },
    ],
  },
  {
    id: "MER-4148",
    reference: "TRD/CBAM/01",
    title: "Carbon border adjustment implementation dispute widens across members",
    summary:
      "Three member states have filed incompatible implementation positions on default carbon values, producing a scheduled-adjacent enforcement gap rather than a headline confrontation.",
    stage: "emerging",
    detectedAt: "2026-09-08",
    firstSignalAt: "2026-08-26",
    confidence: 0.76,
    novelty: 0.58,
    velocity: 0.54,
    actors: ["EU", "DE", "CN", "IN", "BR", "US", "TR"],
    regions: ["Europe", "South America", "Asia-Pacific"],
    tags: ["trade", "regulation", "carbon"],
    analystNote:
      "Low velocity, high persistence. Implementation disputes do not spike; they grind. Useful as a control case against the higher-velocity chokepoint scenarios in the corpus.",
    tailScenario:
      "A court challenge suspends the default-value mechanism for two quarters, creating a de facto exemption period that exporters price as permanent and producers decline to decarbonise against it.",
    signals: [
      {
        id: "S-4148-1",
        source: "Member state implementation note",
        sourceClass: "official",
        observedAt: "2026-08-26",
        channel: "trade",
        headline: "Objection to default carbon values on legal basis",
        detail: "Objection argues the default values are not administratively determinable, which if upheld removes the mechanism entirely.",
        reliability: 0.91,
        weight: 0.7,
        corroborations: 3,
        anomalyZ: 1.9,
      },
      {
        id: "S-4148-2",
        source: "Brussels trade briefing",
        sourceClass: "official",
        observedAt: "2026-09-01",
        channel: "diplomatic",
        headline: "Third incompatible implementation position filed",
        detail: "Positions now diverge on both value determination and covered-goods scope.",
        reliability: 0.87,
        weight: 0.62,
        corroborations: 2,
        anomalyZ: 1.7,
      },
      {
        id: "S-4148-3",
        source: "European steel order book",
        sourceClass: "market",
        observedAt: "2026-09-08",
        channel: "finance",
        headline: "Domestic premium over imported held at 6% despite soft demand",
        detail: "Premium persistence suggests anticipatory pricing rather than current-order strength.",
        reliability: 0.8,
        weight: 0.58,
        corroborations: 3,
        anomalyZ: 1.8,
      },
    ],
    pathways: [
      {
        channel: "trade",
        direction: "mixed",
        magnitude: 0.58,
        lagDays: [40, 140],
        confidence: 0.68,
        mechanism:
          "Implementation divergence fragments a single market into differently-treated segments, raising intra-bloc trade friction at the same time as raising the external barrier.",
        exposures: [
          { nodeId: "EU", exposure: 0.86, impact: 0.42, lagDays: 60, note: "Intra-bloc customs friction replaces external friction" },
          { nodeId: "IN", exposure: 0.7, impact: 0.36, lagDays: 70, note: "Covered-goods compliance cost front-loaded" },
          { nodeId: "BR", exposure: 0.66, impact: 0.33, lagDays: 75, note: "Steel and aluminium diversion risk" },
          { nodeId: "CN", exposure: 0.62, impact: 0.3, lagDays: 65, note: "Embedded-emissions reporting obligation" },
          { nodeId: "TR", exposure: 0.52, impact: 0.26, lagDays: 80, note: "Preferential-access tension" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "mixed",
        magnitude: 0.51,
        lagDays: [60, 200],
        confidence: 0.61,
        mechanism:
          "Procedural divergence is resolvable, but only slowly, and slow resolution is itself a cost to exporters planning capital investment.",
        exposures: [
          { nodeId: "EU", exposure: 0.68, impact: 0.3, lagDays: 90, note: "Legal challenge threatens mechanism timeline" },
          { nodeId: "BR", exposure: 0.48, impact: 0.21, lagDays: 110, note: "Third-country coalition forming" },
        ],
      },
      {
        channel: "finance",
        direction: "mixed",
        magnitude: 0.34,
        lagDays: [20, 70],
        confidence: 0.56,
        mechanism: "Sector-level margin effects; no systemic transmission.",
        exposures: [
          { nodeId: "DE", exposure: 0.5, impact: 0.22, lagDays: 45, note: "Industrial compliance cost capitalised" },
          { nodeId: "INSTL", exposure: 0.34, impact: 0.14, lagDays: 55, note: "Carbon-cost pass-through modelled into estimates" },
        ],
      },
      {
        channel: "energy",
        direction: "mixed",
        magnitude: 0.28,
        lagDays: [120, 300],
        confidence: 0.42,
        mechanism:
          "Long-run only. The instrument changes relative cost of energy-intensive production, not near-term energy balances.",
        exposures: [
          { nodeId: "EU", exposure: 0.4, impact: 0.15, lagDays: 200, note: "Decarbonisation capex deferred under legal uncertainty" },
        ],
      },
    ],
  },
  {
    id: "MER-4152",
    reference: "FIN/SOV/06",
    title: "Sovereign risk repricing after an election result in a commodity exporter",
    summary:
      "A decisive election outcome in a large commodity exporter has produced a rapid, order-driven widening in sovereign spreads, with the curve shape indicating a fiscal-credibility repricing rather than a growth repricing.",
    stage: "active",
    detectedAt: "2026-09-05",
    firstSignalAt: "2026-09-01",
    confidence: 0.9,
    novelty: 0.41,
    velocity: 0.74,
    actors: ["AR", "BR", "US", "EU", "CN", "CBRICKS"],
    regions: ["South America", "Global"],
    tags: ["sovereign debt", "fiscal", "emerging markets"],
    analystNote:
      "The curve is the evidence. A parallel shift signals growth repricing; a steepening at the front end with a stable long end signals the market is pricing fiscal credibility rather than output. This is the latter.",
    tailScenario:
      "Credibility repricing meets a commodity drawdown in the same quarter. Reserves cover the current account but not the maturity wall, and the programme is restructured under a framework that resets domestic demand for a decade.",
    signals: [
      {
        id: "S-4152-1",
        source: "Emerging-market credit desk",
        sourceClass: "market",
        observedAt: "2026-09-01",
        channel: "finance",
        headline: "Front-end spread widens 180bp, long end unmoved",
        detail: "Curve steepening isolates the repricing to fiscal credibility rather than to growth or commodity expectations.",
        reliability: 0.93,
        weight: 0.9,
        corroborations: 6,
        anomalyZ: 4.1,
      },
      {
        id: "S-4152-2",
        source: "Reuters wire",
        sourceClass: "wire",
        observedAt: "2026-09-02",
        channel: "diplomatic",
        headline: "Multilateral engagement requested within 72 hours of the result",
        detail: "An unusually compressed timetable implies the funding calendar, not the political calendar, is driving the outreach.",
        reliability: 0.86,
        weight: 0.66,
        corroborations: 4,
        anomalyZ: 2.4,
      },
      {
        id: "S-4152-3",
        source: "FX desk, São Paulo",
        sourceClass: "market",
        observedAt: "2026-09-03",
        channel: "finance",
        headline: "NDF basis widened against the forward curve",
        detail: "Basis widening indicates hedging demand outstripping available local-currency supply.",
        reliability: 0.82,
        weight: 0.6,
        corroborations: 3,
        anomalyZ: 2.7,
      },
      {
        id: "S-4152-4",
        source: "Commodity trade finance panel",
        sourceClass: "intel",
        observedAt: "2026-09-05",
        channel: "trade",
        headline: "Letter-of-credit confirmations lengthening on sovereign-linked facilities",
        detail: "Confirmation lag is a leading indicator of sovereign stress, running roughly one quarter ahead of the spread.",
        reliability: 0.77,
        weight: 0.64,
        corroborations: 2,
        anomalyZ: 2.2,
      },
    ],
    pathways: [
      {
        channel: "finance",
        direction: "escalatory",
        magnitude: 0.81,
        lagDays: [2, 30],
        confidence: 0.89,
        mechanism:
          "Domestic transmission first through the sovereign curve and the FX basis, then externally through creditor haircuts and programme conditionality.",
        exposures: [
          { nodeId: "BR", exposure: 0.88, impact: 0.64, lagDays: 8, note: "Global risk appetite transmits through the region's benchmark" },
          { nodeId: "AR", exposure: 0.94, impact: 0.71, lagDays: 5, note: "Front-end repricing anchored on fiscal credibility" },
          { nodeId: "CBRICKS", exposure: 0.72, impact: 0.44, lagDays: 20, note: "Programme design and conditionality under negotiation" },
          { nodeId: "INSTL", exposure: 0.6, impact: 0.29, lagDays: 12, note: "EM allocation trimmed at the sovereign level" },
          { nodeId: "SWIFT", exposure: 0.48, impact: 0.24, lagDays: 10, note: "Cross-border funding cost repricing" },
        ],
      },
      {
        channel: "trade",
        direction: "escalatory",
        magnitude: 0.46,
        lagDays: [25, 90],
        confidence: 0.66,
        mechanism:
          "Trade finance terms tighten before trade volumes fall. Import cover is the first macro aggregate to respond.",
        exposures: [
          { nodeId: "AR", exposure: 0.7, impact: 0.36, lagDays: 35, note: "Import cover compresses on confirmation lag" },
          { nodeId: "BR", exposure: 0.5, impact: 0.24, lagDays: 45, note: "Neighbouring trade-credit terms follow regional risk" },
        ],
      },
      {
        channel: "diplomatic",
        direction: "mixed",
        magnitude: 0.5,
        lagDays: [20, 90],
        confidence: 0.68,
        mechanism:
          "Compressed engagement timetable converts a domestic political outcome into a multilateral negotiation with a hard deadline.",
        exposures: [
          { nodeId: "CBRICKS", exposure: 0.6, impact: 0.3, lagDays: 30, note: "Conditionality debate becomes the binding constraint" },
          { nodeId: "US", exposure: 0.48, impact: 0.22, lagDays: 35, note: "Programme participation under domestic review" },
          { nodeId: "EU", exposure: 0.42, impact: 0.18, lagDays: 40, note: "Exposure concentrated in one member" },
        ],
      },
      {
        channel: "energy",
        direction: "mixed",
        magnitude: 0.33,
        lagDays: [60, 180],
        confidence: 0.52,
        mechanism:
          "Commodity export capacity is unchanged; only the fiscal take and repatriation schedule are at risk, which acts on price incentives over quarters.",
        exposures: [
          { nodeId: "AR", exposure: 0.55, impact: 0.24, lagDays: 90, note: "Fiscal take compression discourages further output growth" },
        ],
      },
    ],
  },
];