/** Ambient declarations for non-code assets imported from the project. */

/** Pre-projected Natural Earth country geometry, generated by scripts/build-geo.mjs. */
declare module "@/assets/world-50m.json" {
  const value: {
    v: number;
    countries: { i: string; n: string; d: string; x: number; y: number; r: number }[];
  };
  export default value;
}

/** Natural Earth country boundaries, bundled as TopoJSON. */
declare module "world-atlas/*.json" {
  const value: {
    objects: Record<string, unknown>;
    arcs: unknown;
    transform?: unknown;
    type?: string;
  };
  export default value;
}